worker: yarn build:backend --config ../../app-config.yaml --config ../../app-config.production.yaml
web: yarn workspace backend start --config ../../app-config.yaml --config ../../app-config.production.yaml
