[_]
schema-version = "0.2"
id = "org.broadinstitute.backstage"
name = "BITS Backstage"
authors = ["devnull@broadinstitute.org"]
version = "0.0.1"
source-url = "https://github.com/broadinstitute/backstage"
documentation-url = "https://backstage.broadinstitute.org/catalog/default/component/backstage/docs"


[io.buildpacks]
builder = "gcr.io/buildpacks/builder@sha256:99ea417bcd8b0f576e5387926dc792db609b07642404e2236db4dd1b05f05daf"
exclude = [
    "github-app*",
    "app-config.local.yaml",
    "op.bash",
    "examples",
]

[[io.buildpacks.group]]
id = "google.nodejs.runtime"

[[io.buildpacks.group]]
id = "google.nodejs.yarn"

[[io.buildpacks.group]]
id = "google.config.entrypoint"

[[io.buildpacks.group]]
id = "google.utils.label-image"

[[io.buildpacks.group]]
id = "me/gcs-upload"

  [io.buildpacks.group.script]
  api = "0.10"
  inline = """
curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz
tar -xf google-cloud-cli-linux-x86_64.tar.gz
./google-cloud-sdk/install.sh
gcloud storage cp --recursive node_modules/ gs://${_ARTIFACT_BUCKET}/${_APP}/${_PR}/node_modules
"""
