---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backstage" # Location of package manifests
    groups:
      npm:
        patterns:
          - '*'
        exclude-patterns:
        - '@backstage/*'
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "react*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: 'github-actions'
    directory: '/'
    groups:
      actions:
        patterns:
          - '*'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: 'weekly'
  - package-ecosystem: 'terraform'
    directory: '/deployment/dev/terraform'
    groups:
      terraform_dev:
        patterns:
          - '*'
    schedule:
      # Check for updates to Terraform every week
      interval: 'weekly'
  - package-ecosystem: 'terraform'
    directory: '/deployment/prod/terraform'
    groups:
      terraform_prod:
        patterns:
          - '*'
    schedule:
      # Check for updates to Terraform every week
      interval: 'weekly'
  - package-ecosystem: 'docker'
    directory: '/deployment/backstage'
    groups:
      kubernetes:
        patterns:
          - '*'
    schedule:
      # Check for updates to Docker images every week
      interval: 'weekly'
  - package-ecosystem: 'docker'
    directory: '/backstage'
    groups:
      buildpack:
        patterns:
          - '*'
    schedule:
      # Check for updates to Docker images every week
      interval: 'weekly'
