---
# Disable some built-in rules
config:
  line-length: false
# Fix any fixable errors
fix: true
# Disable inline config comments
noInlineConfig: true
# Disable progress on stdout (only valid at root)
noProgress: true
