---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  title: backstage
  description: my service 
  links:
    - url: https://backstage.broadinstitute.org
      title: backstage
      icon: dashboard
  tags:
  - bits
  - bits-tools
  annotations:
    backstage.io/kubernetes-id: backstage
    github.com/project-slug: broadinstitute/backstage
    google.com/cloudbuild-project-slug: bits-gke-clusters
    google.com/cloudbuild-repo-name: backstage
    google.com/cloudbuild-location: us-east4
    backstage.io/techdocs-ref: dir:.
    
    
spec:
  type: service
  owner: broadinstitute
  lifecycle: production
  
  
