---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  links:
    - url: https://backstage.broadinstitute.org
      title: Backstage
      icon: dashboard
  description: Broad Institute Engineering Portal is an Internal Developer Platform (Spotify Backstage by another name)
  tags:
  - bits
  - kubernetes
  - bits-tools
  annotations:
    backstage.io/kubernetes-id: backstage
    backstage.io/kubernetes-namespace: backstage
    pagerduty.com/integration-key: b14f2c8afb49400bd0ddb48d216ada5a
    github.com/project-slug: broadinstitute/backstage
    google.com/cloudbuild-project-slug: bits-gke-clusters
    google.com/cloudbuild-repo-name: backstage
    google.com/cloudbuild-location: us-east4
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  system: backstage
  domain: orchestration
  owner: devnull
  lifecycle: experimental

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage
  title: Backstage
  description: |
    The Backstage Internal Developer Platform
  links:
    - url: https://backstage.broadinstitute.org
      title: Backstage
      icon: dashboard
  tags:
    - bits
    - bits-tools
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: devnull
  domain: orchestration
