apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  links:
    - url: https://backstage.broadinstitute.org
      title: Backstage
      icon: dashboard
  description: Broad Institute Engineering Portal is an Internal Developer Platform (Spotify Backstage by another name)
  annotations:
    github.com/project-slug: broadinstitute/backstage
    google.com/cloudbuild-project-slug: bits-gke-clusters
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  system: backstage
  #domain: bits-platforms
  owner: devnull
  lifecycle: experimental

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage
  description: |
    The Backstage Internal Developer Platform
  tags:
    - bits
    - kubernetes
    - bits-tools
spec:
  owner: devnull
