apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  title: backstage
  description: test
  annotations:
    github.com/project-slug: broadinstitute/backstage
    
    
spec:
  type: service
  owner: group:default/devnull
  lifecycle: production
