---
site_name: 'BITS Backstage Documentation'

nav:
  - Home: index.md
  - catalog: catalog.md
  - kubernetes: kubernetes.md
  - techdocs: techdocs.md
  - templates: templates.md
  - plugins: plugins.md
  - ADRs: adr/README.md
  - Operations: operations.md

plugins:
  - techdocs-core
