---
site_name: 'BITS Backstage Documentation'

nav:
  - Home: README.md
  - "Software Catalog": catalog.md
  - Kubernetes: kubernetes.md
  - TechDocs: techdocs.md
  - "Software Templates": templates.md
  - "Backstage Plugins": plugins.md
  - Operations: operations.md
  - Release Notes: release-updates.md
  - ADRs: adr/README.md

plugins:
  - techdocs-core
