---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-spack-package
  title: "Add Spack Package"
  description: >-
    Create a new PR with your a new spack package to the SCISOFT Repository.
    Available packages and versions can be found at [packages.spack.io](https://packages.spack.io/).
  tags:
    - recommended
    - spack
    - scisoft
    - production

spec:
  owner: group:devnull
  type: service

  parameters:
    - title: Package Information
      required:
        - name
        - owners
        - email
        - versions
      properties:
        name:
          title: Package Name
          type: string
          description: >-
            Name of package to build and install.
            Available packages and versions can be found at [packages.spack.io](https://packages.spack.io/).

        versions:
          title: 'Package Versions'
          type: array
          description: >-
            List Versions to install. At least one version is required.
          items:
            type: string
            title: Package Versions

        owners:
          title: Requesting Team
          type: string
          description: >-
            Name of the team or lab requesting the package.
        email:
          title: Group Email
          type: string
          description: >-
            Google Group Email address of the team or lab requesting the package.
          pattern: '^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$'
      errorMessage:
        properties:
          email: 'Must be a valid email address'


  steps:
    - id: parsePackageFile
      name: Parse Spack Package File
      action: roadiehq:utils:jsonata
      input:
        expression: '$ ~> | $ | { "spec": $merge([spec, { "package_versions": $reduce($map($split("${{ parameters.versions }}", ","), function($v) { { "name": $v } }), $append, []) }]) } |'
        data:
          apiVersion: bits-package.dev/v1
          kind: SpackPackage
          metadata:
            name: ${{ parameters.name }}
          spec:
            owners:
              - name: ${{ parameters.owners }}
                email: ${{ parameters.email }}
            package_versions:
              - name: 0.0.0
            source: spack-public
            type: spack

    - action: roadiehq:utils:serialize:yaml
      id: serializePackageFile
      name: Serialize The Package File
      input:
        data: ${{ steps.parsePackageFile.output.result }}

    - id: writePackageFile
      name: Create Package YAML File
      action: roadiehq:utils:fs:write
      input:
        path: spack/packages/${{ parameters.name }}.yaml
        content: ${{ steps.serializePackageFile.output.serialized }}

    - id: createPullRequest
      name: createPullRequest
      action: publish:github:pull-request
      input:
        repoUrl: 'github.com?repo=bits-packaging-pipeline&owner=broadinstitute'
        branchName: add-${{ parameters.name }}-package
        title: 'feat: Add ${{ parameters.name }} package to Spack Library'
        description: >-
          This PR adds the ${{ parameters.name }} package to the compiled packages available at the Broad.
          The package will be installed with the following versions: ${{ parameters.versions }}.
  output:
    links:
      - title: View the pull request on GitHub
        icon: github
        url: ${{ steps['createPullRequest'].output.remoteUrl }}
