---
version: 2
updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: fix
    directory: "/"
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      # Check for updates to GitHub Actions every month
      interval: monthly
  - package-ecosystem: "terraform"
    commit-message:
      prefix: fix
    directory: "/"
    groups:
      terraform:
        patterns:
          - "*"
    schedule:
      # Check for updates to Terraform every month
      interval: monthly
