---
name: "Close stale issues and PRs"
permissions:
  actions: write
  contents: read
  issues: write
  pull-requests: write
"on":
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    uses: broadinstitute/shared-workflows/.github/workflows/close-stale.yaml@v5.0.1
