---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-pagerduty-service
  title: Create PagerDuty Service
  description: Creates service in PagerDuty
  tags:
    - pagerduty
    - incident-management
    - alerting
spec:
  owner: devnull
  type: service

  parameters:
    - title: PagerDuty Service
      required:
        - name
        - description
      properties:
        name:
          title: Service Name
          type: string
          description: >-
            The name of the service. Note: You can only select services
            that are owned by your team.
          ui:field: OwnedEntityPicker
          ui:options:
            catalogFilter:
              - kind: Component
        description:
          title: Description
          type: string
          description: The description of the service
        createPagerduty:
          type: boolean
          default: true
          ui:widget: hidden

    - dependencies:
        createPagerduty:
          oneOf:
            - properties:
                createPagerduty:
                  enum:
                    - true

                escalationPolicyId:
                  title: Escalation Policy ID
                  type: string
                  description: The ID of the escalation policy to associate with the service
                  ui:field: SelectFieldFromApi
                  ui:options:
                    title: PagerDuty Escalation Policy
                    description: Select an escalation policy from PagerDuty
                    path: 'pagerduty/escalation_policies'
                    labelSelector: 'label'
                    valueSelector: 'value'
                    placeholder: '---'
                alertGrouping:
                  title: Alert Grouping
                  type: string
                  description: Reduce noise by grouping similar alerts - Defaults to 'None'.
                  enum:
                    - 'time'
                    - 'intelligent'
                    - 'content_based'
                  enumNames:
                    - 'Time-based grouping'
                    - 'Intelligent grouping'
                    - 'Content-based grouping'


            - properties:
                createPagerduty:
                  enum:
                    - false
                pagerdutyIntegrationKey:
                  title: PagerDuty integration key
                  description: This value is ignored if you selected "Yes" for the previous question.
                  type: string

  steps:
    - id: pagerdutyService
      name: Create PagerDuty Service
      if: ${{ parameters.createPagerduty }}
      action: pagerduty:service:create
      input:
        name: ${{ parameters.name | parseEntityRef | pick("name")}}
        description: ${{ parameters.description }}
        escalationPolicyId: ${{ parameters.escalationPolicyId }}
        alertGrouping: ${{ parameters.alertGrouping }}

  output:
    links:
      - title: Open in PagerDuty
        url: ${{ steps['pagerdutyService'].output.serviceUrl }}
    text:
      - title: Integration Key
        text: ${{ steps['pagerdutyService'].output.integrationKey }}
