---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: automation
  description: Tools and services for managing automation.
  title: Automation
  tags:
  - bits-tools
  - automation

  annotations:
    backstage.io/managed-by: backstage
spec:
  owner: bits-aviso
  lifecycle: production
