---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: bits-domains
  description: A collection of all Backstage Domains at BROAD BITS
spec:
  type: file
  targets:
    - ./domains/automation.yaml
    - ./domains/ci-cd.yaml
    - ./domains/cloud.yaml
    - ./domains/containers.yaml
    - ./domains/config-mgmt.yaml
    - ./domains/erp.yaml
    - ./domains/hpc.yaml
    - ./domains/infrastructure-tools.yaml
    - ./domains/monitoring.yaml
    - ./domains/orchestration.yaml
    - ./domains/platform-eng.yaml
    - ./domains/server-operating-systems.yaml
    - ./domains/scientific-software.yaml
    - ./domains/virtualization.yaml
