apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
  namespace: backstage
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    environment: dev
    backstage.io/kubernetes-id: backstage
  annotations:
    iam.gke.io/gcp-service-account: backstage@bits-backstage-dev.iam.gserviceaccount.com
