---
name: "checks"
permissions:
  contents: read
  pull-requests: read
"on":
  pull_request:
    branches:
      - "main"

jobs:
  conventional-commits:
    permissions:
      contents: read
      pull-requests: write
    uses: broadinstitute/shared-workflows/.github/workflows/conventional-commit.yaml@v5.0.1
  linting:
    uses: broadinstitute/shared-workflows/.github/workflows/terraform-lint.yaml@v5.0.1
    with:
      tflint_config_path: "../.tflint.hcl"
      working_directory: "./terraform"
  static_analysis:
    uses: broadinstitute/shared-workflows/.github/workflows/terraform-static-analyze.yaml@v5.0.1
    secrets:
      wf_github_token: ${{ secrets.github_token }}
    with:
      run_trivy: true
      working_directory: "./terraform"
  validation:
    uses: broadinstitute/shared-workflows/.github/workflows/terraform-validate.yaml@v5.0.1
    with:
      use_terragrunt: true
