---
name: 'checks'

'on':
  pull_request:
    branches:
      - 'main'

jobs:
  conventional-commits:
    uses: broadinstitute/shared-workflows/.github/workflows/conventional-commit.yaml@v2.6.1
  validation:
    uses: broadinstitute/shared-workflows/.github/workflows/terraform-validate.yaml@v2.6.1
    with:
      use_terragrunt: true
  linting:
    uses: broadinstitute/shared-workflows/.github/workflows/terraform-lint.yaml@v2.6.1
    with:
      tflint_config_path: '../.tflint.hcl'
      working_directory: './terraform'
  static_analysis:
    uses: broadinstitute/shared-workflows/.github/workflows/terraform-static-analyze.yaml@v2.6.1
    secrets:
      wf_github_token: ${{ secrets.github_token }}
    with:
      run_trivy: true
      working_directory: './terraform'
  zones-output-check:
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
