apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata: # kpt-merge: gcp-load-balancer/http-to-https
  name: http-to-https
  namespace: backstage
  labels:
    app: backstage # kpt-set: ${name}
    environment: prod
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    backstage.io/kubernetes-id: backstage
  annotations:
    internal.kpt.dev/upstream-identifier: 'networking.gke.io|FrontendConfig|gcp-load-balancer|http-to-https'
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
