id: cloudbuildWriteFile
name: Add Cloud Build Annotation
action: roadiehq:utils:fs:write
if: ${{ parameters.cloudbuildAnnotation == true }}
input:
  path: catalog-info.yaml
  content: ${{ steps['cloudbuildAnnotation'].output.result }}
