---
logsBucket: 'gs://1087551700560-us-east4-cloudbuild-logs'

steps:
  - id: build-run-image
    name: 'gcr.io/kaniko-project/executor:latest'
    dir: ${_APP}
    args:
    - '--dockerfile=run.Dockerfile'
    - '--destination=${LOCATION}-docker.pkg.dev/${_REGISTRY_PROJECT}/${_REGISTRY_NAME}/${_APP}-run-image:${_GITHUB_SHA}'
    - '--cache=true'
    - '--cache-copy-layers=false'

  - id: build-image
    name: 'buildpacksio/pack:0.36.4'
    dir: ${_APP}
    entrypoint: pack
    # secretEnv: ['PACK_VOLUME_KEY']
    env:
    - 'NODE_OPTIONS="--max-old-space-size=3686"'
    args:
    - 'build'
    - '${LOCATION}-docker.pkg.dev/${_REGISTRY_PROJECT}/${_REGISTRY_NAME}/${_APP}:${_GITHUB_SHA}'
    - '-t'
    - '${LOCATION}-docker.pkg.dev/${_REGISTRY_PROJECT}/${_REGISTRY_NAME}/${_APP}:${_PR}'
    - '--run-image'
    - '${LOCATION}-docker.pkg.dev/${_REGISTRY_PROJECT}/${_REGISTRY_NAME}/${_APP}-run-image:${_GITHUB_SHA}'
    - '--cache-image'
    - '${LOCATION}-docker.pkg.dev/${_REGISTRY_PROJECT}/${_REGISTRY_NAME}/${_APP}-cache-image:latest'
    - '--publish'
    - '--env'
    - 'NODE_OPTIONS'

  # Pull image for testing
  - id: pull-image-for-testing
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'pull'
      - '${LOCATION}-docker.pkg.dev/${_REGISTRY_PROJECT}/${_REGISTRY_NAME}/${_APP}:${_PR}'

  # Test the image.
  - id: test-docker-image
    name: 'gcr.io/gcp-runtimes/container-structure-test'
    args:
      - 'test'
      - '--image'
      - '${LOCATION}-docker.pkg.dev/${_REGISTRY_PROJECT}/${_REGISTRY_NAME}/${_APP}:${_PR}'
      - '--config'
      - 'container-image-tests.yaml'

images: ['${LOCATION}-docker.pkg.dev/${_REGISTRY_PROJECT}/${_REGISTRY_NAME}/${_APP}:${_PR}']
# artifacts:
#   objects:
#     location: 'gs://${_ARTIFACT_BUCKET}/${_APP}/${_PR}'
#     paths: ["backstage/node_modules"]
