---
substitutions:
  _APP: backstage

steps:
  - id: build-run-image
    name: 'gcr.io/kaniko-project/executor:latest'
    dir: ${_APP}
    args:
    - '--dockerfile=run.Dockerfile'
    - '--destination=${LOCATION}-docker.pkg.dev/${PROJECT_ID}-dev/bits/${_APP}-run-image:${SHORT_SHA}'
    - '--cache=true'

  - id: build-image
    name: 'buildpacksio/pack:0.36.4'
    dir: ${_APP}
    entrypoint: pack
    secretEnv: ['PACK_VOLUME_KEY']
    args:
    - 'build'
    - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}-dev/bits/${_APP}:${SHORT_SHA}'
    - '-t'
    - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}-dev/bits/${_APP}:${_PR_NUMBER}'
    - '--run-image'
    - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}-dev/bits/${_APP}-run-image:${SHORT_SHA}'
    - '--cache-image'
    - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}-dev/bits/${_APP}:latest'
    - '--publish'


  # Pull image for testing
  - id: pull-image-for-testing
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'pull'
      - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}-dev/bits/${_APP}:${SHORT_SHA}'

  - id: create-tags
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}-dev/bits/${_APP}:${SHORT_SHA}'
      - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}-dev/bits/${_APP}:latest'

  # Test the image.
  - id: test-docker-image
    name: 'gcr.io/gcp-runtimes/container-structure-test'
    args:
      - 'test'
      - '--image'
      - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}-dev/bits/${_APP}:${SHORT_SHA}'
      - '--config'
      - 'container-image-tests.yaml'

  # kpt fn eval backstage --image gcr.io/kpt-fn/set-image:v0.1.1 -- \
  #   name=us-east4-docker.pkg.dev/bits-gke-clusters/bits/backstage:latest newTag=0fb8278
  - id: kpt-set-image
    name: 'gcr.io/kpt-dev/kpt:v1.0.0-beta.48'
    args:
      - 'fn'
      - 'eval'
      - 'deployment/dev/${_APP}'
      - '--image'
      - 'gcr.io/kpt-fn/set-image:v0.1.1'
      - '--'
      - 'name=${LOCATION}-docker.pkg.dev/${PROJECT_ID}/bits/${_APP}:latest'
      - 'newName=${LOCATION}-docker.pkg.dev/${PROJECT_ID}-dev/bits/${_APP}'
      - 'newTag=${SHORT_SHA}'

  # kpt fn eval deployment/dev/app --image gcr.io/kpt-fn/set-labels:v0.2.0 --exclude-kind=StatefulSet -- environment=dev
  - id: kpt-set-labels
    name: 'gcr.io/kpt-dev/kpt:v1.0.0-beta.48'
    args:
      - 'fn'
      - 'eval'
      - 'deployment/dev/${_APP}'
      - '--image'
      - 'gcr.io/kpt-fn/set-labels:v0.2.0'
      - '--'
      - 'environment=dev'

  # kpt fn eval --image gcr.io/kpt-fn/apply-setters:v0.2.0 -- branch_name=$BRANCH_NAME
  - id: kpt-apply-setters
    name: 'gcr.io/kpt-dev/kpt:v1.0.0-beta.48'
    args:
      - 'fn'
      - 'eval'
      - 'deployment/dev/${_APP}'
      - '--image'
      - 'gcr.io/kpt-fn/apply-setters:v0.2.0'
      - '--'
      - 'branch_name=${BRANCH_NAME}'

  # gke-deploy server side Dry Run on the dev cluster.
  - id: gke-deploy-dry-run
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - 'run'
      - '--server-dry-run'
      - '--output=dry-run'
      - '--recursive'
      - '--filename=deployment/dev/${_APP}'
      - '--location=${LOCATION}'
      - '--project=${PROJECT_ID}-dev'
      - '--cluster=gke-autopilot-01-dev'
      # - '--verbose'

  # Deploy to the dev cluster.
  - id: gke-deploy-dev
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - 'run'
      - '--recursive'
      - '--timeout=10m'
      - '--filename=deployment/dev/${_APP}'
      - '--location=${LOCATION}'
      - '--project=${PROJECT_ID}-dev'
      - '--cluster=gke-autopilot-01-dev'
      # - '--verbose'

#   # gke-deploy server side Dry Run on the Prod cluster.
#   # This is the only step run against the prod cluster.
#   # It sources the manifests from the prod directory as a validation step.
  - id: gke-deploy-dry-run-prod
    name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - 'run'
      - '--server-dry-run'
      - '--output=dry-run-prod'
      - '--recursive'
      - '--filename=deployment/prod/${_APP}'
      - '--location=${LOCATION}'
      - '--project=${PROJECT_ID}'
      - '--cluster=gke-autopilot-01-prod'
#       # - '--verbose'
options:
  machineType: 'E2_HIGHCPU_8'

availableSecrets:
  secretManager:
  - versionName: projects/broad-bits-devnull-secrets/secrets/cloudbuild-pack-volume-key-backstage/versions/latest
    env: 'PACK_VOLUME_KEY'
images:
  - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}-dev/bits/${_APP}'
  - '${LOCATION}-docker.pkg.dev/${PROJECT_ID}-dev/bits/${_APP}:latest'
