---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      actions:
        patterns:
          - "*"
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /terraform
    groups:
      terraform:
        patterns:
          - "*"
    schedule:
      interval: weekly
