---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: data-transfer
  description: |
    Managed tools facilitating data transfer for the Broad
  title: 'Data Transfer System'
  tags:
    - data-transfer
  annotations:
    backstage.io/managed-by: backstage
spec:
  owner: bits-aviso
  domain: infrastructure-tools
  lifecycle: production
