---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: network-access
  description: |
    Network access for the Broad
  title: 'Network Access'
  tags:
    - networking
  annotations:
    backstage.io/managed-by: backstage
spec:
  owner: spaceballs
  lifecycle: production
