---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  annotations:
    backstage.io/managed-by: backstage
  description: PagerDuty incident management platform
  name: pagerduty
  tags:
    - incident-management
    - pagerduty
    - software
  title: PagerDuty
spec:
  domain: infrastructure-tools
  lifecycle: production
  owner: devnull
